const hre = require("hardhat");

async function main() {
  console.log("Deploying SudokuVerifier contract...");

  // First we need to deploy the UltraVerifier (generated by bb.js)
  // For now, we'll use a placeholder address
  // In production, you would deploy the actual verifier contract first

  const placeholderVerifierAddress =
    "0x0000000000000000000000000000000000000000";

  console.log("Note: Using placeholder verifier address.");
  console.log("You need to:");
  console.log("1. Generate Verifier.sol using bb.js");
  console.log("2. Deploy the Verifier contract");
  console.log("3. Update this script with the actual verifier address");

  const SudokuVerifier = await hre.ethers.getContractFactory("SudokuVerifier");
  const sudokuVerifier = await SudokuVerifier.deploy(
    placeholderVerifierAddress
  );

  await sudokuVerifier.waitForDeployment();

  const address = await sudokuVerifier.getAddress();
  console.log(`SudokuVerifier deployed to: ${address}`);

  // Save deployment info
  const fs = require("fs");
  const deploymentInfo = {
    network: hre.network.name,
    sudokuVerifier: address,
    ultraVerifier: placeholderVerifierAddress,
    timestamp: new Date().toISOString(),
  };

  fs.writeFileSync("deployment.json", JSON.stringify(deploymentInfo, null, 2));

  console.log("Deployment info saved to deployment.json");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
